#!/usr/bin/env node
'use strict';

// Seed the RSVP storage tables with starter data so John & Diana can
// test the system end-to-end before bulk-importing the real guest list.
//
// Usage:
//   $env:RSVP_STORAGE_CONNECTION = "<full connection string>"
//   node scripts/seed-rsvp.js [--reset] [--phone +15551234567]
//
// Flags:
//   --reset        Delete existing test parties before seeding (rsvpParties.PK
//                  in the seeded set only — does NOT wipe real guest data).
//   --phone <E.164> Override John's phone with a real number you control (for
//                   live SMS testing). Otherwise uses a clearly-fake placeholder.

const path = require('path');
const Module = require('module');

// Resolve _lib relative to the api/ folder so we don't have to duplicate code.
const apiRoot = path.resolve(__dirname, '..', 'api');
const originalResolve = Module._resolveFilename;
Module._resolveFilename = function (request, parent, ...rest) {
  if (request.startsWith('./_lib/') || request.startsWith('../_lib/')) {
    const rebased = path.resolve(apiRoot, request.replace(/^\.\.?\/_lib\//, '_lib/'));
    return originalResolve.call(this, rebased, parent, ...rest);
  }
  return originalResolve.call(this, request, parent, ...rest);
};

const storage = require(path.join(apiRoot, '_lib', 'storage'));
const auth = require(path.join(apiRoot, '_lib', 'auth'));

const args = process.argv.slice(2);
const RESET = args.includes('--reset');
const phoneFlagIdx = args.indexOf('--phone');
const JOHN_PHONE = (phoneFlagIdx >= 0 && args[phoneFlagIdx + 1]) || '+15555550100';

if (!process.env.RSVP_STORAGE_CONNECTION) {
  console.error('ERROR: RSVP_STORAGE_CONNECTION env var is required.');
  console.error('  Get it from the Azure portal -> Storage account -> Access keys -> Connection string.');
  process.exit(1);
}
if (!process.env.RSVP_MAGIC_SECRET) {
  // Magic links aren't generated by this script, but auth.js validates secret
  // length when imported. Set a throwaway so the import succeeds.
  process.env.RSVP_MAGIC_SECRET = 'seed-script-placeholder-secret-not-used-anywhere-32+chars-aaa';
}

const SEED_PARTIES = [
  {
    partyId: 'p_johndiana',
    displayName: 'John & Diana',
    locale: 'en',
    phone: JOHN_PHONE,
    plusOneAllowed: false,
    kidsAllowed: false,
    group: 'family',
    notes: 'The couple themselves (test party).',
    members: [
      { firstName: 'John', lastName: 'Lien', role: 'primary', isKid: false, locale: 'en' },
      { firstName: 'Diana', lastName: 'Guajan', role: 'primary', isKid: false, locale: 'es' }
    ]
  },
  {
    partyId: 'p_testfam_garcia',
    displayName: 'García Family',
    locale: 'es',
    phone: '', // no phone — exercises silent-path / no-reminder behavior
    plusOneAllowed: true,
    kidsAllowed: true,
    group: 'family',
    notes: 'Placeholder family of 3 — 2 adults + 1 child. Replace with real guest before launch.',
    members: [
      { firstName: 'Carlos', lastName: 'García', role: 'primary', isKid: false, locale: 'es' },
      { firstName: 'María', lastName: 'García', role: 'primary', isKid: false, locale: 'es' },
      { firstName: 'Lucía', lastName: 'García', role: 'child', isKid: true, locale: 'es' }
    ]
  },
  {
    partyId: 'p_testsolo_smith',
    displayName: 'Jane Smith',
    locale: 'en',
    phone: '+15555550199',
    plusOneAllowed: true,
    kidsAllowed: false,
    group: 'friends',
    notes: 'Placeholder solo guest with plus-one allowed. Replace with real guest before launch.',
    members: [
      { firstName: 'Jane', lastName: 'Smith', role: 'primary', isKid: false, locale: 'en' },
      { firstName: '', lastName: '', role: 'plusone', isKid: false, locale: 'en' }
    ]
  }
];

async function deletePartyData(partyId) {
  const c = storage.getClients();
  // Best-effort delete of all rows in each table for this partyId.
  for (const tableClient of [c.parties, c.members, c.responses, c.smslog]) {
    try {
      const filter = `PartitionKey eq '${partyId.replace(/'/g, "''")}'`;
      for await (const e of tableClient.listEntities({ queryOptions: { filter } })) {
        try {
          await tableClient.deleteEntity(e.partitionKey, e.rowKey);
        } catch (err) {
          if (!err || err.statusCode !== 404) throw err;
        }
      }
    } catch (err) {
      console.warn(`  warn deleting from ${tableClient.tableName}: ${err && err.message}`);
    }
  }
}

async function run() {
  console.log('Ensuring tables exist…');
  await storage.ensureTables();
  console.log('  OK.\n');

  if (RESET) {
    for (const p of SEED_PARTIES) {
      console.log(`Resetting party ${p.partyId} (${p.displayName})…`);
      await deletePartyData(p.partyId);
    }
    console.log('');
  }

  for (const seed of SEED_PARTIES) {
    console.log(`Seeding party ${seed.partyId} (${seed.displayName})`);
    await storage.upsertParty({
      partyId: seed.partyId,
      displayName: seed.displayName,
      locale: seed.locale,
      phone: seed.phone,
      plusOneAllowed: seed.plusOneAllowed,
      kidsAllowed: seed.kidsAllowed,
      optedOutOfSms: false,
      group: seed.group,
      notes: seed.notes,
      reminderCount: 0
    });
    for (let i = 0; i < seed.members.length; i += 1) {
      const m = seed.members[i];
      const memberId = `m${i + 1}_${auth.generateId().slice(0, 8)}`;
      await storage.upsertMember(seed.partyId, {
        memberId,
        firstName: m.firstName,
        lastName: m.lastName,
        role: m.role,
        isKid: m.isKid,
        locale: m.locale
      });
      console.log(`  member ${memberId}: ${m.firstName || '(blank)'} ${m.lastName || '(blank)'} [${m.role}${m.isKid ? '/kid' : ''}]`);
    }
    console.log('');
  }

  const settings = await storage.getSettings();
  console.log('Current settings:');
  console.log(`  remindersEnabled: ${settings.remindersEnabled}`);
  console.log(`  remindersStopOnUtc: ${settings.remindersStopOnUtc}`);
  console.log('');

  console.log('Done. Try the form with name "John Lien" or "Diana Guajan".');
  console.log('Magic-link token for the John & Diana party (for /api/rsvp/magic?t=...):');
  try {
    console.log(`  ${auth.signMagicToken('p_johndiana')}`);
  } catch (err) {
    console.log(`  (set RSVP_MAGIC_SECRET to generate a real token; got ${err && err.message})`);
  }
}

run().catch((err) => {
  console.error('SEED FAILED:', err && err.message);
  if (err && err.stack) console.error(err.stack);
  process.exit(2);
});
